export const ERR_QUESTION_CAPTION_EMPTY = 'ERR_QUESTION_CAPTION_EMPTY'
export const ERR_QUESTION_UNKNOWN_TYPE = 'ERR_QUESTION_UNKNOWN_TYPE'
export const ERR_QUESTION_INVALID_CONFIG_TYPE = 'ERR_QUESTION_INVALID_CONFIG_TYPE'

export const ERR_QUESTION_ANSWER_OPTION_INVALID_ID = 'ERR_QUESTION_ANSWER_OPTION_INVALID_ID'
export const ERR_QUESTION_ANSWER_OPTION_EMPTY = 'ERR_QUESTION_ANSWER_OPTION_EMPTY'
export const ERR_QUESTION_ANSWER_INVALID_TYPE = 'ERR_QUESTION_ANSWER_INVALID_TYPE'
export const ERR_QUESTION_NO_ANSWER = 'ERR_QUESTION_NO_ANSWER'

export const ERR_QUESTION_ANSWER_CHILD_INVALID = 'ERR_QUESTION_ANSWER_CHILD_INVALID'

export const ERR_QUESTION_ANSWER_EMPTY = 'ERR_QUESTION_ANSWER_EMPTY'